CREATE TABLE "TODO" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL,
    "CONTENT" VARCHAR(255),
    "TAG" VARCHAR(255)
);
CREATE SEQUENCE "TODO_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;